In [4]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
# Graphics in SVG format are more sharp and legible
%config InlineBackend.figure_format = 'svg'
pd.set_option("display.precision", 2)

data = pd.read_csv('titanic_train.csv',
                  index_col='PassengerId')
data.head(5)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.28,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.92,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.10,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.05,NaN,S

In [7]:
data.describe()

       Survived  Pclass     Age   SibSp   Parch    Fare
count    891.00  891.00  714.00  891.00  891.00  891.00
mean       0.38    2.31   29.70    0.52    0.38   32.20
std        0.49    0.84   14.53    1.10    0.81   49.69
min        0.00    1.00    0.42    0.00    0.00    0.00
25%        0.00    2.00   20.12    0.00    0.00    7.91
50%        0.00    3.00   28.00    0.00    0.00   14.45
75%        1.00    3.00   38.00    1.00    0.00   31.00
max        1.00    3.00   80.00    8.00    6.00  512.33

In [8]:
data[(data['Embarked'] == 'C') & (data.Fare > 200)].head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.52,B58 B60,C
259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.33,NaN,C
300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.52,B58 B60,C
312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.38,B57 B59 B63 B66,C
378,0,1,"Widener, Mr. Harry Elkins",male,27.0,0,2,113503,211.50,C82,C

In [9]:
data[(data['Embarked'] == 'C') & (data.Fare > 200)].sort_values(by='Fare', ascending=False).head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.33,NaN,C
680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.33,B51 B53 B55,C
738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.33,B101,C
312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.38,B57 B59 B63 B66,C
743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.38,B57 B59 B63 B66,C

In [10]:
def age_category(age):
    '''
    < 30 -> 1
    >= 30, <55 -> 2
    >= 55 -> 3
    '''
    if age < 30:
        return 1
    elif age < 55:
        return 2
    elif age >= 55:
        return 3

age_categories = [age_category(age) for age in data.Age]
data['Age_category'] = age_categories

In [11]:
data['Age_category'] = data['Age'].apply(age_category)

In [27]:
# 1. Сколько мужчин / женщин было на борту?
#print(f"{data[data['Sex'] == "male"].shape[0]} мужчин и  {data[data['Sex'] == "female"].shape[0]} женщин")

print((data['Sex'].value_counts())['male'], "мужчин", (data['Sex'].value_counts())['female'], "женщин")

577 мужчин 314 женщин

In [28]:
#2. Определите распределение функции Pclass. Теперь Для мужчин и женщин отдельно. Сколько людей из второго класса было на борту?

#методы революз. как изменяет значения функция. методы оценки функции. коэф. детерминации.

#просто распределение
pclass = data['Pclass'].value_counts().sort_index()
print(pclass, '\n')

pclass2 = data.groupby(['Sex','Pclass']).size().unstack()
print(pclass2, '\n')

print("Ответ:", pclass2.loc['male',2])

Pclass
1    216
2    184
3    491
Name: count, dtype: int64

Pclass    1    2    3
Sex
female   94   76  144
male    122  108  347

Ответ: 108

In [48]:
#3. Каковы медиана и стандартное отклонение Fare?. Округлите до 2-х знаков после запятой.

fare_med = data['Fare'].median()
fare_std = data['Fare'].std()
print(f" медиана {fare_med:.2f} стандартное отклонение {fare_std:.2f} ")

 медиана 14.45 стандартное отклонение 49.69

In [25]:
# 4. Правда ли, что средний возраст выживших людей выше, чем у пассажиров, которые в конечном итоге умерли?

#survived_data = data['Survived'].value_counts()
#print(f"Выжили {survived_data.get(1,0)} Погибли {survived_data.get(0,0)}", '\n')

#survived_data_age = data.loc[data['Survived'] == 1, 'Age'].mean()
#print(f"Ср. возр. выживших: {survived_data_age:.2f}", '\n')

#unsurvived_data_age = data.loc[data['Survived'] == 0, 'Age'].mean()
#print(f"Ср. возр. погибших: {unsurvived_data_age:.2f}", '\n')

#print("Да") if survived_data_age > unsurvived_data_age else print("Нет")

survived_data_easy = data.groupby('Survived')['Age'].mean()
print(survived_data_easy, '\n')
print("Да" if survived_data_easy[1] > survived_data_easy[0] else "Нет")

Survived
0    30.63
1    28.34
Name: Age, dtype: float64

Нет

In [22]:
#5. Это правда, что пассажиры моложе 30 лет. выжили чаще, чем те, кому больше 60 лет. Каковы доли выживших людей среди молодых и пожилых людей?

young_survived = data.loc[data['Age'] < 30, 'Survived']
old_survived = data.loc[data['Age'] > 60, 'Survived']
print("Да" if young_survived.count() > old_survived.count() else "Нет")
print(f"Молодых {young_survived.mean() * 100:.2f}%, Пожилых {old_survived.mean() * 100:.2f}%")

#survived_data = data['Survived'].value_counts()
#survived_count = survived_data.get(1,0)

#survived_young = data.loc[(data['Survived'] == 1) & (data['Age'] < 30)].shape[0]

#total_young = data.loc[data['Age'] < 30].shape[0]

#survived_old = data.loc[(data['Survived']==1) & (data['Age'] > 60)].shape[0]

#total_old = data.loc[data['Age'] > 60].shape[0]

#print(f"{(survived_young/total_young)*100:.1f}% среди молодёжи и {(survived_old/total_old)*100:.1f}% среди пожилых", '\n')

#2.data['AgeGroup'] = data['Age'].apply(lambda x: 'Моложе 30' if x < 30 else 'Старше 60' if x > 60 else 'Другие')

#survival_rates = data.groupby('AgeGroup')['Survived'].mean() * 100
#young_rate = survival_rates.get('Моложе 30', 0)
#old_rate = survival_rates.get('Старше 60', 0)

Да
Молодых 40.62%, Пожилых 22.73%

In [123]:
#6.Правда ли, что женщины выживали чаще мужчин? Каковы доли выживших людей среди мужчин и женщин?

groupped = data.groupby('Sex')['Survived'].mean() * 100
female_rate = groupped.get('female', 0)
male_rate = groupped.get('male', 0)
print(f"{female_rate:.1f}% среди женщин и {male_rate:.1f}% среди мужчин")

74.2% среди женщин и 18.9% среди мужчин

In [131]:
# 7. Какое имя наиболее популярно среди пассажиров мужского пола?

def get_first_name(full_name):
    # 1) часть после запятой
    after_comma = full_name.split(',')[1]
     # 2) часть после первой точки ()
    after_dot = after_comma.split('.')[1]
     # 3) первое слово — собственно имя
    first_name = after_dot.strip().split()[0]
    return first_name

male_names = data.loc[data['Sex'] == 'male', 'Name'].apply(get_first_name)

name_counts = male_names.value_counts()

print("Наиболее популярное мужское имя:", name_counts.index[0])

PassengerId
1           Owen
5        William
6          James
7        Timothy
8          Gosta
         ...
884    Frederick
885        Henry
887       Juozas
890         Karl
891      Patrick
Name: Name, Length: 577, dtype: object
Наиболее популярное мужское имя: William

In [26]:
# 8. Как средний возраст мужчин / женщин зависит от Pclass? Выберите все правильные утверждения:

result=[]
sort = data.groupby(['Sex', 'Pclass'])['Age'].mean()
if(sort['male',1]>40):
    result.append('В среднем мужчины 1 класса старше 40 лет')
if(sort['female',1]>40):
    result.append('В среднем женщины 1 класса старше 40 лет')
q3=False
for pclass in [1, 2, 3]:
    men_age = sort['male', pclass]
    women_age = sort['female', pclass]
    if (men_age>women_age):q3=True

if q3 ==True: result.append('Мужчины всех классов в среднем старше, чем женщины того же класса')

sort2 = data.groupby('Pclass')['Age'].mean()
if sort2[1]>sort2[2]>sort2[3]:
    result.append('В среднем, пассажиры первого класса старше, чем пассажиры 2-го класса, которые старше, чем пассажиры 3-го класса.')

for q in result:
    print(q)

В среднем мужчины 1 класса старше 40 лет
Мужчины всех классов в среднем старше, чем женщины того же класса
В среднем, пассажиры первого класса старше, чем пассажиры 2-го класса, которые старше, чем пассажиры 3-го класса.